### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by fredcwbr** [pjz/TMDAng#5]
Howdy,

Is this project still alive?

**Comment by pjz** [comment]
...ish?  It's in maintenance mode, I ported it to py3 and mostly use the filter end.  Contributions welcome!

**Comment by fredcwbr** [comment]
> ...ish? It's in maintenance mode, I ported it to py3 and mostly use the filter end. Contributions welcome!

Hi!

I'm looking for some help. Did clone almost everything i could grab on Wayback, and others. Using you fixes could make TMDA  work on a Deb BookWorm, but struggling on the CGI ., 

Can't figure what i'm  doing wrong  (most likely not installed the user part). But not being able to go past the session creation/recovery , for the first time. 

Would it be that you managed to get some notes on the CGI (user installation procedure?) that would be lying around?

Thanks for the response, .. .

Have a nice Day

**Comment by pjz** [comment]
Sorry, I don't.  All I can suggest is the Wayback Machine.  You might start at https://web.archive.org/web/20101004032334/http://tmda.sourceforge.net/tmda-cgi/modes.html and read the pages under 'install' and see if they help.  Good general knowledge of installing and running CGIs is probably also required.

**Comment by fredcwbr** [comment]
Thanks for the reply. I'll do my best, and keep you posted. Eventually, will fork and ask for pull ...


Untill then,

Be safe , 
And thanks .
